# ParticleX Configuration

avatar: https://pixiv.cat/131558857.jpg

background:
    - https://pixiv.cat/110486537.jpg
    # - https://pixiv.cat/140645189.jpg
    # - https://pixiv.cat/131089295.jpg

loading: /images/loading.gif

colors:
    - "#ffa2c4"
    - "#00bcd4"
    - "#03a9f4"
    - "#00a596"
    - "#ff7d73"

menu:
    Home:
        name: house
        theme: solid
        link: /
    About:
        name: id-card
        theme: solid
        link: /about
    Archives:
        name: box-archive
        theme: solid
        link: /archives
    Categories:
        name: bookmark
        theme: solid
        link: /categories
    Tags:
        name: tags
        theme: solid
        link: /tags

card:
    enable: true
    description: |
        资深机器人爱好者
    iconLinks:
    friendLinks:
        Argvchs: https://argvchs.github.io

footer:
    since: 2022
    ICP:
        enable: false
        code:
        link:

polyfill:
    enable: true
    features:
        - default

highlight:
    enable: true
    style: github

math:
    enable: true

preview:
    enable: true

crypto:
    enable: false

search:
    enable: false

giscus:
    enable: false
    src: https://giscus.app/client.js
    repo:
    repoID:
    category:
    categoryID:
    mapping: pathname
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: bottom
    theme: preferred_color_scheme
    lang:

gitalk:
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    language:
    proxy:

waline:
    enable: false
    serverURL:
    locale:
    commentCount: true
    pageview: false
    emoji:
        - https://unpkg.com/@waline/emojis@1.2.0/weibo
        - https://unpkg.com/@waline/emojis@1.2.0/alus
        - https://unpkg.com/@waline/emojis@1.2.0/bilibili
        - https://unpkg.com/@waline/emojis@1.2.0/qq
        - https://unpkg.com/@waline/emojis@1.2.0/tieba
        - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
    meta:
        - nick
        - mail
        - link
    requiredMeta:
        - nick
    lang:
    wordLimit: 0
    login: enable
    pageSize: 10

twikoo:
    enable: false
    envID:
    region:
    path: location.pathname
    lang:
